### ISSUE TITLE
Bug: Bot reports LBE online when is offline

### ISSUE THREAD

**Issue by wilkcom** [nycmeshnet/nycmesh-support-bot#72] opened 2023-02-16 03:15 UTC
This bug comes from ubiquiti. The AP will report good connection with the client even when is disconnected.
Suggestion: grab IP of LBE from Omni and ping it.

**Comment by andybaumgar** [comment] 2023-02-16 04:03
Thanks for reporting this.  Is there an example you could link to on Slack?

**Comment by wilkcom** [comment] 2023-02-16 13:22
here is example
https://nycmesh.slack.com/archives/C679UKBUK/p1676515365757849

**Comment by andybaumgar** [comment] 2023-02-16 22:23
Thanks!

**Comment by andybaumgar** [comment] 2023-02-16 22:27
Duplicate of https://github.com/nycmeshnet/nycmesh-support-bot/issues/73

**Comment by andybaumgar** [comment] 2023-02-16 22:28
@wilkcom We are discussing this issue more in https://github.com/nycmeshnet/nycmesh-support-bot/issues/73.  The UISP data can be old, so we are going to add a disclaimer and show the last update time.

**Closed as completed** 2023-05-11 01:36 UTC
